on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x, 16.x, 18.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Fixup bson dependency for Node.js 12
        run: if node -e 'process.exitCode = 1 - process.version.startsWith("v12")'; then npm install bson@4; fi
        shell: bash
      - name: Test
        run: npm test
